### PR TITLE
210 indicate timeframe over which metric is calculated and make it configurable

### PR DESCRIPTION
**Pull request by epolak01**

### CODE REVIEW

**Review by fonarevvichka — CHANGES_REQUESTED** [review]
Looks pretty good, I would change months to "mo" in the timeframe box so that is is a little smaller. units should be clear and they are also in the tooltip
Also I would get rid of the up and down arrows, I feel they are not needed
Also maybe throw an extra disclaimer in the tooltip that longer timeframes might take longer

**Review by fonarevvichka — CHANGES_REQUESTED** [review]
Sorry looks like I was wrong I think the months looks better than mo
Also you seem to be missing some error checking. Entering a non integer causes a non-descript alert to pop up "can't communicate with api"

**Comment by epolak01** [comment]
> Sorry looks like I was wrong I think the months looks better than mo
> Also you seem to be missing some error checking. Entering a non integer causes a non-descript alert to pop up "can't communicate with api"

Could you recreate the conditions of that error, because I'm not able to recreate that. I set 12 months as the default so when you put nonsense in the box it should just query for 12 months.

**Comment by fonarevvichka** [comment]
Here's an example of the problem I'm running into. Now it just says "scores unavailable"
image

**Comment by fonarevvichka** [comment]
Also putting something like -1 makes the timeframe 0 rather than 12

**Comment by fonarevvichka** [comment]
> > Sorry looks like I was wrong I think the months looks better than mo
> > Also you seem to be missing some error checking. Entering a non integer causes a non-descript alert to pop up "can't communicate with api"
> 
> Could you recreate the conditions of that error, because I'm not able to recreate that. I set 12 months as the default so when you put nonsense in the box it should just query for 12 months.

I feel like it should just round to the nearest whole int if its a positive int and go to 12 if is below 0

**Review by fonarevvichka — APPROVED** [review]
lgtm

**Pull request merged**
